# Generated by Django 2.0.9 on 2018-11-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20181026_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
    ]
